services:
  - type: web
    name: langflow
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: langflow run --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0